language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("MinFinder"))`); Pkg.pin("MinFinder"); Pkg.resolve()'
  - julia -e 'using MinFinder; @assert isdefined(:MinFinder); @assert typeof(MinFinder) === Module'
  - julia test/runtests.jl
